# EDA Notebook
### Purpose: Extract descriptive statistics about the dataset
### Reference: https://github.com/mdeff/fma/blob/master/analysis.ipynb

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
# load features.csv
features_path = os.path.join("..","..", "fma_metadata", "features.csv")
features = pd.read_csv(features_path, index_col=[0], header=[0,1,2])
features.head()

feature    chroma_cens                                                    \
statistics    kurtosis
number              01        02        03        04        05        06
track_id
2             7.180653  5.230309  0.249321  1.347620  1.482478  0.531371
3             1.888963  0.760539  0.345297  2.295201  1.654031  0.067592
5             0.527563 -0.077654 -0.279610  0.685883  1.937570  0.880839
10            3.702245 -0.291193  2.196742 -0.234449  1.367364  0.998411
20           -0.193837 -0.198527  0.201546  0.258556  0.775204  0.084794

feature                                             ...   tonnetz            \
statistics                                          ...       std
number            07        08        09        10  ...        04        05
track_id                                            ...
2           1.481593  2.691455  0.866868  1.341231  ...  0.054125  0.012226
3           1.366848  1.054094  0.108103  0.619185  ...  0.063831  0.014212
5          -0.923192 -0.927232  0.666617  1.038546  ...  0.040730  0.012691
10          1.770694  1.604566  0.521217  1.982386  ...  0.074358  0.017952
20         -0.289294 -0.816410  0.043851 -0.804761  ...  0.095003  0.022492

feature                     zcr                                          \
statistics             kurtosis       max      mean    median       min
number            06         01        01        01        01        01
track_id
2           0.012111   5.758890  0.459473  0.085629  0.071289  0.000000
3           0.017740   2.824694  0.466309  0.084578  0.063965  0.000000
5           0.014759   6.808415  0.375000  0.053114  0.041504  0.000000
10          0.013921  21.434212  0.452148  0.077515  0.071777  0.000000
20          0.021355  16.669037  0.469727  0.047225  0.040039  0.000977

feature
statistics      skew       std
number            01        01
track_id
2           2.089872  0.061448
3           1.716724  0.069330
5           2.193303  0.044861
10          3.542325  0.040800
20          3.189831  0.030993

[5 rows x 518 columns]

In [9]:
# load tracks.csv
tracks_path = os.path.join("..","..", "fma_metadata", 'tracks.csv')
tracks = pd.read_csv(tracks_path, index_col=[0], header=[0,1])
tracks.head()

            album                                                     \
         comments         date_created        date_released engineer
track_id
2               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
3               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
5               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
10              0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN
20              0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN

                                                                          \
         favorites id                                information listens
track_id
2                4  1                                    <p></p>    6073
3                4  1                                    <p></p>    6073
5                4  1                                    <p></p>    6073
10               4  6                                        NaN   47632
20               2  4  <p>Â "spiritual songs" from Nicky Cook</p>    2710

                        ...       track                         \
         producer tags  ... information interest language_code
track_id                ...
2             NaN   []  ...         NaN     4656            en
3             NaN   []  ...         NaN     1470            en
5             NaN   []  ...         NaN     1933            en
10            NaN   []  ...         NaN    54881            en
20            NaN   []  ...         NaN      978            en

                                                                              \
                                                    license listens lyricist
track_id
2         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1293      NaN
3         Attribution-NonCommercial-ShareAlike 3.0 Inter...     514      NaN
5         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1151      NaN
10        Attribution-NonCommercial-NoDerivatives (aka M...   50135      NaN
20        Attribution-NonCommercial-NoDerivatives (aka M...     361      NaN


         number publisher tags            title
track_id
2             3       NaN   []             Food
3             4       NaN   []     Electric Ave
5             6       NaN   []       This World
10            1       NaN   []          Freeway
20            3       NaN   []  Spiritual Level

[5 rows x 52 columns]

In [12]:
# load genres.csv
genres_path = os.path.join("..","..", "fma_metadata", 'genres.csv')
genres = pd.read_csv(genres_path, index_col=[0])
genres.head()

          #tracks  parent          title  top_level
genre_id
1            8693      38    Avant-Garde         38
2            5271       0  International          2
3            1752       0          Blues          3
4            4126       0           Jazz          4
5            4106       0      Classical          5

# Size

In [15]:
print('{} tracks, {} artists, {} albums, {} genres'.format(
    len(tracks), len(tracks['artist', 'id'].unique()),
    len(tracks['album', 'id'].unique()),
    sum(genres['#tracks'] > 0)))

106574 tracks, 16341 artists, 14854 albums, 161 genres

In [16]:
mean_duration = tracks['track', 'duration'].mean()
print('track duration: {:.0f} days total, {:.0f} seconds average'.format(
    sum(tracks['track', 'duration']) / 3600 / 24,
    mean_duration))

track duration: 343 days total, 278 seconds average

In [19]:
genres.sort_values(by='#tracks', ascending = False)

          #tracks  parent                  title  top_level
genre_id
38          38154       0           Experimental         38
15          34413       0             Electronic         15
12          32923       0                   Rock         12
1235        14938       0           Instrumental       1235
10          13845       0                    Pop         10
...           ...     ...                    ...        ...
493             4     651          Western Swing          9
173             4      86  N. Indian Traditional          2
377             1      19              Deep Funk         14
178             0       4                 Be-Bop          4
175             0      86              Bollywood          2

[163 rows x 4 columns]